from nlab_modbus.core.register_specs import RegisterSpec, RegisterType

GEIGER_REGISTER_MAP = {
    # Holding registers
    "rs485_mb_addr": RegisterSpec(reg_type=RegisterType.HOLDING, address=0, dtype="int16", min=1, max=254,
        description="Modbus address on RS485"),
    "rs485_baud": RegisterSpec(reg_type=RegisterType.HOLDING, address=1, dtype="int16", min=96, max=10000, scale=100,
        description="RS485 baud rate [100 bps units] (115200 = 1152)"),
    "pwm_enable": RegisterSpec(reg_type=RegisterType.HOLDING, address=2, dtype="int16", min=0, max=1,
        description="HV supply enable for GM tube [0/1]"),
    "pwm_set_voltage": RegisterSpec(reg_type=RegisterType.HOLDING, address=3, dtype="int16", min=50, max=650, unit="V",
        description="HV converter output voltage setpoint [50–650 V]"),
    "pulse_trig_level_mv": RegisterSpec(reg_type=RegisterType.HOLDING, address=4, dtype="int16", min=0, max=2500, unit="mV", password_protected=True,
        description="GM tube pulse comparator threshold voltage [0–2500 mV]"),
    "dummy_1": RegisterSpec(reg_type=RegisterType.HOLDING, address=5, dtype="int16", min=0, max=0, unit="reserved",
        description="Reserved"),
    "pwm_freq_khz": RegisterSpec(reg_type=RegisterType.HOLDING, address=6, dtype="int16", min=10, max=500, unit="kHz", password_protected=True,
        description="HV converter switching frequency [10–500 kHz]"),
    "pwm_max_duty": RegisterSpec(reg_type=RegisterType.HOLDING, address=7, dtype="int16", min=0, max=90, unit="%", password_protected=True,
        description="HV converter maximum PWM duty cycle [0–90 %]"),
    "pwm_outvolt_comp": RegisterSpec(
        reg_type=RegisterType.HOLDING, address=8, dtype="int16", min=-1000, max=1000, scale=0.01, unit="%", password_protected=True,
        description="Output voltage correction (gain) [0.01 %]"),
    "dummy_2": RegisterSpec(reg_type=RegisterType.HOLDING, address=9, dtype="int16", min=0, max=0, unit="reserved",
        description="Reserved"),
    "scale_coeff_p1_a2": RegisterSpec(reg_type=RegisterType.HOLDING, address=10, dtype="int16", min=-32000, max=32000, password_protected=True,
        description="Dose calibration polynomial 1 — a2 coefficient mantissa"),
    "scale_exp_p1_a2": RegisterSpec(reg_type=RegisterType.HOLDING, address=11, dtype="int16", min=-9, max=9, password_protected=True,
        description="Dose calibration polynomial 1 — a2 coefficient exponent"),
    "scale_coeff_p1_a1": RegisterSpec(reg_type=RegisterType.HOLDING, address=12, dtype="int16", min=-32000, max=32000, password_protected=True,
        description="Dose calibration polynomial 1 — a1 coefficient mantissa"),
    "scale_exp_p1_a1": RegisterSpec(reg_type=RegisterType.HOLDING, address=13, dtype="int16", min=-9, max=9, password_protected=True,
        description="Dose calibration polynomial 1 — a1 coefficient exponent"),
    "scale_coeff_p1_a0": RegisterSpec(reg_type=RegisterType.HOLDING, address=14, dtype="int16", min=-32000, max=32000, password_protected=True,
        description="Dose calibration polynomial 1 — a0 coefficient mantissa"),
    "scale_exp_p1_a0": RegisterSpec(reg_type=RegisterType.HOLDING, address=15, dtype="int16", min=-9, max=9, password_protected=True,
        description="Dose calibration polynomial 1 — a0 coefficient exponent"),
    "scale_coeff_th": RegisterSpec(reg_type=RegisterType.HOLDING, address=16, dtype="int16", min=-32000, max=32000, password_protected=True,
        description="Dose calibration polynomial switching threshold mantissa"),
    "scale_exp_th": RegisterSpec(reg_type=RegisterType.HOLDING, address=17, dtype="int16", min=-9, max=9, password_protected=True,
        description="Dose calibration polynomial switching threshold exponent"),
    "scale_coeff_p2_a2": RegisterSpec(reg_type=RegisterType.HOLDING, address=18, dtype="int16", min=-32000, max=32000, password_protected=True,
        description="Dose calibration polynomial 2 (above threshold) — a2 coefficient mantissa"),
    "scale_exp_p2_a2": RegisterSpec(reg_type=RegisterType.HOLDING, address=19, dtype="int16", min=-9, max=9, password_protected=True,
        description="Dose calibration polynomial 2 — a2 coefficient exponent"),
    "scale_coeff_p2_a1": RegisterSpec(reg_type=RegisterType.HOLDING, address=20, dtype="int16", min=-32000, max=32000, password_protected=True,
        description="Dose calibration polynomial 2 (above threshold) — a1 coefficient mantissa"),
    "scale_exp_p2_a1": RegisterSpec(reg_type=RegisterType.HOLDING, address=21, dtype="int16", min=-9, max=9, password_protected=True,
        description="Dose calibration polynomial 2 — a1 coefficient exponent"),
    "scale_coeff_p2_a0": RegisterSpec(reg_type=RegisterType.HOLDING, address=22, dtype="int16", min=-32000, max=32000, password_protected=True,
        description="Dose calibration polynomial 2 (above threshold) — a0 coefficient mantissa"),
    "scale_exp_p2_a0": RegisterSpec(reg_type=RegisterType.HOLDING, address=23, dtype="int16", min=-9, max=9, password_protected=True,
        description="Dose calibration polynomial 2 — a0 coefficient exponent"),
    "pid_p_vout": RegisterSpec(reg_type=RegisterType.HOLDING, address=24, dtype="int16", min=0, max=1000, password_protected=True,
        description="Output voltage PID proportional gain"),
    "pid_i_vout": RegisterSpec(reg_type=RegisterType.HOLDING, address=25, dtype="int16", min=0, max=1000, password_protected=True,
        description="Output voltage PID integral gain"),
    "adc_freq_khz": RegisterSpec(reg_type=RegisterType.HOLDING, address=26, dtype="int16", min=1, max=20, unit="kHz", password_protected=True,
        description="Built-in ADC sampling frequency / HV voltage regulation loop frequency"),
    "adc_filter_coeff": RegisterSpec(reg_type=RegisterType.HOLDING, address=27, dtype="int16", min=0, max=100, password_protected=True,
        description="HV voltage measurement filter coefficient"),
    "pass_static": RegisterSpec(reg_type=RegisterType.HOLDING, address=28, dtype="int16", min=-32767, max=32767,
        description="Service password"),
    # Input registers
    "hardware_version": RegisterSpec(reg_type=RegisterType.INPUT, address=0, dtype="int16", min=-32768, max=32767,
        description="Hardware version (TYPE.VERSION in high and low byte)"),
    "firmware_version": RegisterSpec(reg_type=RegisterType.INPUT, address=1, dtype="int16", min=-32768, max=32767,
        description="Firmware version (MAJOR.MINOR in high and low byte)"),
    "pulses": RegisterSpec(reg_type=RegisterType.INPUT, address=2, dtype="int16", min=-32768, max=32767,
        description="GM tube detected pulse counter (uint16, wraps at 65535)"),
    "pulses_per_sec": RegisterSpec(reg_type=RegisterType.INPUT, address=3, dtype="int16", min=-32768, max=32767, unit="cps",
        description="GM tube pulse frequency [cps]"),
    "dose_level_msvh": RegisterSpec(reg_type=RegisterType.INPUT, address=4, dtype="int16", min=-32768, max=32767, unit="mSv/h",
        description="Calculated dose rate [mSv/h]"),
    "dose_msv": RegisterSpec(reg_type=RegisterType.INPUT, address=5, dtype="int16", min=-32768, max=32767, unit="mSv",
        description="Accumulated dose since startup [mSv]"),
    "rs485_rx_frames_cnt": RegisterSpec(reg_type=RegisterType.INPUT, address=6, dtype="int16", min=-32768, max=32767,
        description="Modbus received frames counter"),
    "rs485_rx_crc_err_cnt": RegisterSpec(reg_type=RegisterType.INPUT, address=7, dtype="int16", min=-32768, max=32767,
        description="Modbus received frames with CRC error counter"),
    "rs485_rx_bad_req_cnt": RegisterSpec(reg_type=RegisterType.INPUT, address=8, dtype="int16", min=-32768, max=32767,
        description="Modbus bad request counter (e.g. unsupported command)"),
    "cpu_temp": RegisterSpec(reg_type=RegisterType.INPUT, address=9, dtype="int16", min=-32768, max=32767, unit="*C",
        description="CPU temperature [°C]"),
    "board_temp": RegisterSpec(reg_type=RegisterType.INPUT, address=10, dtype="int16", min=-32768, max=32767, unit="*C", scale=0.01,
        description="PCB sensor temperature [0.01 °C]"),
    "eeprom_error": RegisterSpec(reg_type=RegisterType.INPUT, address=11, dtype="int16", min=0, max=2,
        description="EEPROM error: 1=hardware error, 2=CRC error"),
    "supply_voltage": RegisterSpec(reg_type=RegisterType.INPUT, address=12, dtype="int16", min=-32768, max=32767, unit="V", scale=0.01,
        description="5V supply voltage [0.01 V]"),
    "hv_voltage": RegisterSpec(reg_type=RegisterType.INPUT, address=13, dtype="int16", min=-32768, max=32767, unit="V",
        description="Measured HV voltage [V]"),
    "pulse_integer": RegisterSpec(reg_type=RegisterType.INPUT, address=14, dtype="int16", min=-32768, max=32767, unit="mV",
        description="GM tube pulse integrator output voltage [mV]"),
    "gm_supply_fault": RegisterSpec(reg_type=RegisterType.INPUT, address=15, dtype="int16", min=0, max=1,
        description="HV supply overload/overheat status"),
    "pwm_duty": RegisterSpec(reg_type=RegisterType.INPUT, address=16, dtype="int16", min=-32768, max=32767, scale=0.1, unit="%",
        description="HV converter current PWM duty cycle [0.1 %]"),
    "vout_ripple": RegisterSpec(reg_type=RegisterType.INPUT, address=17, dtype="int16", min=-32768, max=32767, unit="mV",
        description="Output HV voltage ripple (estimated over last second) [mV]"),
    "pwm_cmpss_action": RegisterSpec(reg_type=RegisterType.INPUT, address=18, dtype="int16", min=-32768, max=32767,
        description="Hardware HV protection triggered (status clears after 1 s)"),
    "pid_saturation": RegisterSpec(reg_type=RegisterType.INPUT, address=19, dtype="int16", min=-32768, max=32767,
        description="PID controller integral accumulator saturation"),
}
