from nlab_modbus.core.register_specs import RegisterSpec, RegisterType

PSU_REGISTER_MAP = {
    # Holding registers
    "rs485_mb_addr": RegisterSpec(reg_type=RegisterType.HOLDING, address=0, dtype="int16", min=1, max=254,
        description="Modbus address on RS485"),
    "rs485_baud": RegisterSpec(reg_type=RegisterType.HOLDING, address=1, dtype="int16", min=96, max=10000, scale=100,
        description="RS485 baud rate [100 bps units] (115200 = 1152)"),
    "pwm_enable": RegisterSpec(reg_type=RegisterType.HOLDING, address=2, dtype="int16", min=0, max=1,
        description="HV supply enable [0/1]"),
    "pwm_set_voltage": RegisterSpec(reg_type=RegisterType.HOLDING, address=3, dtype="int16", min=50, max=1500, unit="V",
        description="HV converter output voltage setpoint [50–1500 V]"),
    "pwm_freq_khz": RegisterSpec(reg_type=RegisterType.HOLDING, address=4, dtype="int16", min=10, max=100, unit="kHz", password_protected=True,
        description="HV converter switching frequency [10–100 kHz]"),
    "pwm_max_duty": RegisterSpec(reg_type=RegisterType.HOLDING, address=5, dtype="int16", min=0, max=60, unit="%", password_protected=True,
        description="HV converter maximum PWM duty cycle [0–60 %]"),
    "pwm_outvolt_comp": RegisterSpec(
        reg_type=RegisterType.HOLDING, address=6, dtype="int16", min=-1000, max=1000, scale=0.01, unit="%", password_protected=True,
        description="Output voltage correction (gain) [0.01 %]"),
    "pid_p_vout": RegisterSpec(reg_type=RegisterType.HOLDING, address=7, dtype="int16", min=0, max=1000, password_protected=True,
        description="Output voltage PID proportional gain"),
    "pid_i_vout": RegisterSpec(reg_type=RegisterType.HOLDING, address=8, dtype="int16", min=0, max=1000, password_protected=True,
        description="Output voltage PID integral gain"),
    "adc_freq_khz": RegisterSpec(reg_type=RegisterType.HOLDING, address=9, dtype="int16", min=1, max=20, unit="kHz", password_protected=True,
        description="Built-in ADC sampling frequency / HV voltage regulation loop frequency"),
    "adc_filter_coeff": RegisterSpec(reg_type=RegisterType.HOLDING, address=10, dtype="int16", min=0, max=100, password_protected=True,
        description="HV voltage measurement filter coefficient"),
    "pass_static": RegisterSpec(reg_type=RegisterType.HOLDING, address=11, dtype="int16", min=-32767, max=32767,
        description="Service password"),
    # Input registers
    "hardware_version": RegisterSpec(reg_type=RegisterType.INPUT, address=0, dtype="int16", min=-32768, max=32767,
        description="Hardware version (TYPE.VERSION in high and low byte)"),
    "firmware_version": RegisterSpec(reg_type=RegisterType.INPUT, address=1, dtype="int16", min=-32768, max=32767,
        description="Firmware version (MAJOR.MINOR in high and low byte)"),
    "rs485_rx_frames_cnt": RegisterSpec(reg_type=RegisterType.INPUT, address=2, dtype="int16", min=-32768, max=32767,
        description="Modbus received frames counter"),
    "rs485_rx_crc_err_cnt": RegisterSpec(reg_type=RegisterType.INPUT, address=3, dtype="int16", min=-32768, max=32767,
        description="Modbus received frames with CRC error counter"),
    "rs485_rx_bad_req_cnt": RegisterSpec(reg_type=RegisterType.INPUT, address=4, dtype="int16", min=-32768, max=32767,
        description="Modbus bad request counter (e.g. unsupported command)"),
    "cpu_temp": RegisterSpec(reg_type=RegisterType.INPUT, address=5, dtype="int16", min=-32768, max=32767, unit="*C",
        description="CPU temperature [°C]"),
    "board_temp": RegisterSpec(reg_type=RegisterType.INPUT, address=6, dtype="int16", min=-32768, max=32767, unit="*C", scale=0.01,
        description="PCB sensor temperature [0.01 °C]"),
    "eeprom_error": RegisterSpec(reg_type=RegisterType.INPUT, address=7, dtype="int16", min=0, max=2,
        description="EEPROM error: 1=hardware error, 2=CRC error"),
    "supply_voltage": RegisterSpec(reg_type=RegisterType.INPUT, address=8, dtype="int16", min=-32768, max=32767, unit="V", scale=0.01,
        description="5V supply voltage [0.01 V]"),
    "hv_voltage": RegisterSpec(reg_type=RegisterType.INPUT, address=9, dtype="int16", min=-32768, max=32767, unit="V",
        description="Measured HV voltage [V]"),
    "pwm_duty": RegisterSpec(reg_type=RegisterType.INPUT, address=10, dtype="int16", min=-32768, max=32767, scale=0.1, unit="%",
        description="HV converter current PWM duty cycle [0.1 %]"),
    "hv_current": RegisterSpec(reg_type=RegisterType.INPUT, address=11, dtype="int16", min=-32768, max=32767, unit="uA",
        description="Measured HV current [µA]"),
    "vout_ripple": RegisterSpec(reg_type=RegisterType.INPUT, address=12, dtype="int16", min=-32768, max=32767, unit="mV",
        description="Output HV voltage ripple (estimated over last second) [mV]"),
    "pwm_cmpss_action": RegisterSpec(reg_type=RegisterType.INPUT, address=13, dtype="int16", min=-32768, max=32767,
        description="Hardware HV protection triggered (status clears after 1 s)"),
    "pid_saturation": RegisterSpec(reg_type=RegisterType.INPUT, address=14, dtype="int16", min=-32768, max=32767,
        description="PID controller integral accumulator saturation"),
    "pmt_temp": RegisterSpec(reg_type=RegisterType.INPUT, address=15, dtype="int16", min=-32768, max=32767, unit="*C",
        description="Temperature on powered PMT module [0.01 °C]"),
}
