from nlab_modbus.core.register_specs import RegisterSpec, RegisterType

SIPM_REGISTER_MAP = {
    # Holding registers
    "rs485_mb_addr": RegisterSpec(reg_type=RegisterType.HOLDING, address=0, dtype="int16", min=1, max=254,
        description="Modbus address on RS485"),
    "rs485_baud": RegisterSpec(reg_type=RegisterType.HOLDING, address=1, dtype="int16", min=96, max=10000, scale=100,
        description="RS485 baud rate [100 bps units] (115200 = 1152)"),
    "vout_pwr_en": RegisterSpec(reg_type=RegisterType.HOLDING, address=2, dtype="int16", min=0, max=1,
        description="SiPM converter output enable"),
    "vout_set": RegisterSpec(reg_type=RegisterType.HOLDING, address=3, dtype="int16", min=1500, max=7800, unit="mV", scale=0.01,
        description="SiPM output voltage setpoint [10 mV]"),
    "pid_p_vout": RegisterSpec(reg_type=RegisterType.HOLDING, address=4, dtype="int16", min=0, max=1000, password_protected=True,
        description="Output voltage PID proportional gain"),
    "pid_i_vout": RegisterSpec(reg_type=RegisterType.HOLDING, address=5, dtype="int16", min=0, max=1000, password_protected=True,
        description="Output voltage PID integral gain"),
    "sipm_comp_en": RegisterSpec(reg_type=RegisterType.HOLDING, address=6, dtype="int16", min=0, max=1,
        description="SiPM temperature compensation enable"),
    "sipm_comp_tref": RegisterSpec(reg_type=RegisterType.HOLDING, address=7, dtype="int16", min=-5000, max=5000, scale=0.01, unit="*C",
        description="SiPM voltage compensation reference temperature [0.01 °C]"),
    "sipm_comp_ct": RegisterSpec(reg_type=RegisterType.HOLDING, address=8, dtype="int16", min=-100, max=100, unit="mv/*C",
        description="Temperature compensation coefficient [mV/°C]"),
    "vout_corr": RegisterSpec(reg_type=RegisterType.HOLDING, address=9, dtype="int16", min=-1000, max=1000, scale=0.01, password_protected=True,
        description="Output voltage correction (gain) [0.01 %]"),
    "led_drv_enable": RegisterSpec(reg_type=RegisterType.HOLDING, address=10, dtype="int16", min=0, max=1,
        description="Calibration LED driver enable"),
    "led_drv_period_us": RegisterSpec(reg_type=RegisterType.HOLDING, address=11, dtype="int16", min=1, max=650, unit="us", password_protected=True,
        description="Calibration pulse period [µs]"),
    "led_drv_duration_ns": RegisterSpec(
        reg_type=RegisterType.HOLDING, address=12, dtype="int16", min=1, max=100, scale=10.0, unit="ns", password_protected=True,
        description="Calibration pulse duration [10 ns]"),
    "led_drv_imod_reg": RegisterSpec(reg_type=RegisterType.HOLDING, address=13, dtype="int16", min=0, max=0xFFF, password_protected=True,
        description="LED driver modulation current register value"),
    "led_drv_ibias_reg": RegisterSpec(reg_type=RegisterType.HOLDING, address=14, dtype="int16", min=0, max=0xFFF, password_protected=True,
        description="LED driver bias current register value"),
    "pass_static": RegisterSpec(reg_type=RegisterType.HOLDING, address=15, dtype="int16", min=-32767, max=32767,
        description="Service password"),
    # Input registers
    "hardware_version": RegisterSpec(reg_type=RegisterType.INPUT, address=0, dtype="int16", min=-32768, max=32767,
        description="Hardware version (TYPE.VERSION in high and low byte)"),
    "firmware_version": RegisterSpec(reg_type=RegisterType.INPUT, address=1, dtype="int16", min=-32768, max=32767,
        description="Firmware version (MAJOR.MINOR in high and low byte)"),
    "vout_overload": RegisterSpec(reg_type=RegisterType.INPUT, address=2, dtype="int16", min=0, max=1,
        description="SiPM power supply overload status"),
    "sipm_voltage_10mv": RegisterSpec(reg_type=RegisterType.INPUT, address=3, dtype="int16", min=-32768, max=32767, unit="V", scale=0.01,
        description="SiPM output voltage [0.01 V]"),
    "sipm_current_ua": RegisterSpec(reg_type=RegisterType.INPUT, address=4, dtype="int16", min=-32768, max=32767, unit="A", scale=0.000001,
        description="Current shunt voltage drop [µA]"),
    "board_temp_adc": RegisterSpec(reg_type=RegisterType.INPUT, address=5, dtype="int16", min=-32768, max=32767, unit="*C", scale=0.01,
        description="Current sensor temperature [0.01 °C]"),
    "rs485_rx_frames_cnt": RegisterSpec(reg_type=RegisterType.INPUT, address=6, dtype="int16", min=-32768, max=32767,
        description="Modbus received frames counter"),
    "rs485_rx_crc_err_cnt": RegisterSpec(reg_type=RegisterType.INPUT, address=7, dtype="int16", min=-32768, max=32767,
        description="Modbus received frames with CRC error counter"),
    "rs485_rx_bad_req_cnt": RegisterSpec(reg_type=RegisterType.INPUT, address=8, dtype="int16", min=-32768, max=32767,
        description="Modbus bad request counter (e.g. unsupported command)"),
    "cpu_temp": RegisterSpec(reg_type=RegisterType.INPUT, address=9, dtype="int16", min=-32768, max=32767, unit="*C",
        description="CPU temperature [°C]"),
    "board_temp": RegisterSpec(reg_type=RegisterType.INPUT, address=10, dtype="int16", min=-32768, max=32767, unit="*C", scale=0.01,
        description="PCB sensor temperature [0.01 °C]"),
    "eeprom_error": RegisterSpec(reg_type=RegisterType.INPUT, address=11, dtype="int16", min=0, max=2,
        description="EEPROM error: 1=hardware error, 2=CRC error"),
    "supply_voltage": RegisterSpec(reg_type=RegisterType.INPUT, address=12, dtype="int16", min=-32768, max=32767, unit="V", scale=0.01,
        description="5V supply voltage [0.01 V]"),
    "adc_sipm_vout": RegisterSpec(reg_type=RegisterType.INPUT, address=13, dtype="int16", min=-32768, max=32767, unit="V", scale=0.01,
        description="Additional SiPM voltage from internal ADC [0.01 V]"),
    "sipm_board_temp": RegisterSpec(reg_type=RegisterType.INPUT, address=14, dtype="int16", min=-32768, max=32767, unit="*C", scale=0.01,
        description="External SiPM module temperature sensor [0.01 °C]"),
    "sipm_correct_voltage_mv": RegisterSpec(reg_type=RegisterType.INPUT, address=15, dtype="int16", min=-32768, max=32767, unit="mV",
        description="Temperature compensation correction voltage [mV]"),
    "vout_supply_fault": RegisterSpec(reg_type=RegisterType.INPUT, address=16, dtype="int16", min=0, max=1,
        description="SiPM converter power supply overload/overheat status"),
    "ext_amp_supply_fault": RegisterSpec(reg_type=RegisterType.INPUT, address=17, dtype="int16", min=0, max=1,
        description="External SiPM amplifier supply overload/overheat status"),
    "led_drv_temp": RegisterSpec(reg_type=RegisterType.INPUT, address=18, dtype="int16", min=-32768, max=32767, unit="*C",
        description="LED driver temperature"),
    "led_drv_status": RegisterSpec(reg_type=RegisterType.INPUT, address=19, dtype="int16", min=-32768, max=32767,
        description="LED driver operating status (see LTC5100 datasheet p. 42)"),
    "vout_ripple": RegisterSpec(reg_type=RegisterType.INPUT, address=20, dtype="int16", min=-32768, max=32767, unit="mV",
        description="Output HV voltage ripple (estimated over last second) [mV]"),
    "pid_saturation": RegisterSpec(reg_type=RegisterType.INPUT, address=21, dtype="int16", min=-32768, max=32767,
        description="PID controller integral accumulator saturation"),
}
