from nlab_modbus.core.register_specs import RegisterSpec, RegisterType

SIPM_REGISTER_MAP = {
    # Holding registers
    "rs485_mb_addr": RegisterSpec(reg_type=RegisterType.HOLDING, address=0, dtype="int16", min=1, max=254),
    "rs485_baud": RegisterSpec(reg_type=RegisterType.HOLDING, address=1, dtype="int16", min=96, max=10000, scale=100),
    "vout_pwr_en": RegisterSpec(reg_type=RegisterType.HOLDING, address=2, dtype="int16", min=0, max=1),
    "vout_set": RegisterSpec(reg_type=RegisterType.HOLDING, address=3, dtype="int16", min=1500, max=7800, unit="mV", scale=0.01),
    "pid_p_vout": RegisterSpec(reg_type=RegisterType.HOLDING, address=4, dtype="int16", min=0, max=1000, password_protected=True),
    "pid_i_vout": RegisterSpec(reg_type=RegisterType.HOLDING, address=5, dtype="int16", min=0, max=1000, password_protected=True),
    "sipm_comp_en": RegisterSpec(reg_type=RegisterType.HOLDING, address=6, dtype="int16", min=0, max=1),
    "sipm_comp_tref": RegisterSpec(reg_type=RegisterType.HOLDING, address=7, dtype="int16", min=-5000, max=5000, scale=0.01, unit="*C"),
    "sipm_comp_ct": RegisterSpec(reg_type=RegisterType.HOLDING, address=8, dtype="int16", min=-100, max=100, unit="mv/*C"),
    "vout_corr": RegisterSpec(reg_type=RegisterType.HOLDING, address=9, dtype="int16", min=-1000, max=1000, scale=0.01, password_protected=True),
    "led_drv_enable": RegisterSpec(reg_type=RegisterType.HOLDING, address=10, dtype="int16", min=0, max=1),
    "led_drv_period_us": RegisterSpec(reg_type=RegisterType.HOLDING, address=11, dtype="int16", min=1, max=650, unit="us", password_protected=True),
    "led_drv_duration_ns": RegisterSpec(
        reg_type=RegisterType.HOLDING, address=12, dtype="int16", min=1, max=100, scale=10.0, unit="ns", password_protected=True
    ),
    "led_drv_imod_reg": RegisterSpec(reg_type=RegisterType.HOLDING, address=13, dtype="int16", min=0, max=0xFFF, password_protected=True),
    "led_drv_ibias_reg": RegisterSpec(reg_type=RegisterType.HOLDING, address=14, dtype="int16", min=0, max=0xFFF, password_protected=True),
    "pass_static": RegisterSpec(reg_type=RegisterType.HOLDING, address=15, dtype="int16", min=-32767, max=32767),
    # Input registers
    "hardware_version": RegisterSpec(reg_type=RegisterType.INPUT, address=0, dtype="int16", min=-32768, max=32767),
    "firmware_version": RegisterSpec(reg_type=RegisterType.INPUT, address=1, dtype="int16", min=-32768, max=32767),
    "vout_overload": RegisterSpec(reg_type=RegisterType.INPUT, address=2, dtype="int16", min=0, max=1),
    "sipm_voltage_10mv": RegisterSpec(reg_type=RegisterType.INPUT, address=3, dtype="int16", min=-32768, max=32767, unit="V", scale=0.01),
    "sipm_current_ua": RegisterSpec(reg_type=RegisterType.INPUT, address=4, dtype="int16", min=-32768, max=32767, unit="A", scale=0.000001),
    "board_temp_adc": RegisterSpec(reg_type=RegisterType.INPUT, address=5, dtype="int16", min=-32768, max=32767, unit="*C", scale=0.01),
    "rs485_rx_frames_cnt": RegisterSpec(reg_type=RegisterType.INPUT, address=6, dtype="int16", min=-32768, max=32767),
    "rs485_rx_crc_err_cnt": RegisterSpec(reg_type=RegisterType.INPUT, address=7, dtype="int16", min=-32768, max=32767),
    "rs485_rx_bad_req_cnt": RegisterSpec(reg_type=RegisterType.INPUT, address=8, dtype="int16", min=-32768, max=32767),
    "cpu_temp": RegisterSpec(reg_type=RegisterType.INPUT, address=9, dtype="int16", min=-32768, max=32767, unit="*C"),
    "board_temp": RegisterSpec(reg_type=RegisterType.INPUT, address=10, dtype="int16", min=-32768, max=32767, unit="*C", scale=0.01),
    "eeprom_error": RegisterSpec(reg_type=RegisterType.INPUT, address=11, dtype="int16", min=0, max=2),
    "supply_voltage": RegisterSpec(reg_type=RegisterType.INPUT, address=12, dtype="int16", min=-32768, max=32767, unit="V", scale=0.01),
    "adc_sipm_vout": RegisterSpec(reg_type=RegisterType.INPUT, address=13, dtype="int16", min=-32768, max=32767, unit="V", scale=0.01),
    "sipm_board_temp": RegisterSpec(reg_type=RegisterType.INPUT, address=14, dtype="int16", min=-32768, max=32767, unit="*C", scale=0.01),
    "sipm_correct_voltage_mv": RegisterSpec(reg_type=RegisterType.INPUT, address=15, dtype="int16", min=-32768, max=32767, unit="mV"),
    "vout_supply_fault": RegisterSpec(reg_type=RegisterType.INPUT, address=16, dtype="int16", min=0, max=1),
    "ext_amp_supply_fault": RegisterSpec(reg_type=RegisterType.INPUT, address=17, dtype="int16", min=0, max=1),
    "led_drv_temp": RegisterSpec(reg_type=RegisterType.INPUT, address=18, dtype="int16", min=-32768, max=32767, unit="*C"),
    "led_drv_status": RegisterSpec(reg_type=RegisterType.INPUT, address=19, dtype="int16", min=-32768, max=32767),
    "vout_ripple": RegisterSpec(reg_type=RegisterType.INPUT, address=20, dtype="int16", min=-32768, max=32767, unit="mV"),
    "pid_saturation": RegisterSpec(reg_type=RegisterType.INPUT, address=21, dtype="int16", min=-32768, max=32767),
}
